// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1398.RoboRaiderStarterCode;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.CANTalon;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;
import edu.wpi.first.wpilibj.TalonSRX;
import edu.wpi.first.wpilibj.VictorSP;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static CANTalon driveTrainSubfrontLeftMotor;
    public static CANTalon driveTrainSubrearLeftMotor;
    public static CANTalon driveTrainSubfrontRightMotor;
    public static CANTalon driveTrainSubrearRightMotor;
    public static RobotDrive driveTrainSubdriveTrain;
    public static SpeedController shooterSubsystemSpeedController1;
    public static SpeedController shooterSubsystemSpeedController2;
    public static SpeedController shooterSubsystemSpeedController3;
    public static CANTalon liftArm_PulleyCANTalon1;
    public static CANTalon liftArm_PulleyCANTalon2;
    public static CANTalon horizontalArmSubsystemCANTalon1;
    public static CANTalon horizontalArmSubsystemCANTalon2;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrainSubfrontLeftMotor = new CANTalon(1);
        LiveWindow.addActuator("DriveTrainSub", "frontLeftMotor", driveTrainSubfrontLeftMotor);
        
        driveTrainSubrearLeftMotor = new CANTalon(2);
        LiveWindow.addActuator("DriveTrainSub", "rearLeftMotor", driveTrainSubrearLeftMotor);
        
        driveTrainSubfrontRightMotor = new CANTalon(3);
        LiveWindow.addActuator("DriveTrainSub", "frontRightMotor", driveTrainSubfrontRightMotor);
        
        driveTrainSubrearRightMotor = new CANTalon(4);
        LiveWindow.addActuator("DriveTrainSub", "rearRightMotor", driveTrainSubrearRightMotor);
        
        driveTrainSubdriveTrain = new RobotDrive(driveTrainSubfrontLeftMotor, driveTrainSubrearLeftMotor,
              driveTrainSubfrontRightMotor, driveTrainSubrearRightMotor);
        
        driveTrainSubdriveTrain.setSafetyEnabled(true);
        driveTrainSubdriveTrain.setExpiration(0.1);
        driveTrainSubdriveTrain.setSensitivity(0.5);
        driveTrainSubdriveTrain.setMaxOutput(1.0);

        shooterSubsystemSpeedController1 = new TalonSRX(1);
        LiveWindow.addActuator("ShooterSubsystem", "Speed Controller 1", (TalonSRX) shooterSubsystemSpeedController1);
        
        shooterSubsystemSpeedController2 = new VictorSP(2);
        LiveWindow.addActuator("ShooterSubsystem", "Speed Controller 2", (VictorSP) shooterSubsystemSpeedController2);
        
        shooterSubsystemSpeedController3 = new Talon(3);
        LiveWindow.addActuator("ShooterSubsystem", "Speed Controller 3", (Talon) shooterSubsystemSpeedController3);
        
        liftArm_PulleyCANTalon1 = new CANTalon(8);
        LiveWindow.addActuator("Lift Arm_Pulley", "CAN Talon 1", liftArm_PulleyCANTalon1);
        
        liftArm_PulleyCANTalon2 = new CANTalon(9);
        LiveWindow.addActuator("Lift Arm_Pulley", "CAN Talon 2", liftArm_PulleyCANTalon2);
        
        horizontalArmSubsystemCANTalon1 = new CANTalon(10);
        LiveWindow.addActuator("HorizontalArmSubsystem", "CAN Talon 1", horizontalArmSubsystemCANTalon1);
        
        horizontalArmSubsystemCANTalon2 = new CANTalon(11);
        LiveWindow.addActuator("HorizontalArmSubsystem", "CAN Talon 2", horizontalArmSubsystemCANTalon2);
        

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
